[[repos]]
repo  = "https://github.com/pre-commit/pre-commit-hooks"
rev   = "v6.0.0"
hooks = [
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer", args = ["--fix"] },
  { id = "trailing-whitespace" }
]

[[repos]]
repo  = "https://github.com/astral-sh/ruff-pre-commit"
rev   = "v0.15.2"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" }
]

[[repos]]
repo  = "https://github.com/rvben/rumdl-pre-commit"
rev   = "v0.1.24"
hooks = [{ id = "rumdl-fmt" }]

[[repos]]
repo  = "https://github.com/astral-sh/uv-pre-commit"
rev   = "0.10.4"
hooks = [{ id = "uv-lock" }]

# https://github.com/astral-sh/ty/issues/269
[[repos]]
repo  = "local"
hooks = [
  {
    id       = "ty-check",
    name     = "ty-check",
    language = "python",
    entry    = "ty check",
    pass_filenames = false,
    args = ["--python=.venv/"],
    additional_dependencies = ["ty"]
  },
]
