name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: publish to pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: install uv
        uses: astral-sh/setup-uv@v6
      - name: install python
        run: uv python install 3.13
      - name: build
        run: uv build
      - name: smoke test (wheel, cli)
        run: uv run --isolated --no-project --with dist/*.whl fsweep --help
      - name: smoke test (wheel, module)
        run: uv run --isolated --no-project --with dist/*.whl python -m fsweep --help
      - name: smoke test (sdist, cli)
        run: uv run --isolated --no-project --with dist/*.tar.gz fsweep --help
      - name: smoke test (sdist, module)
        run: uv run --isolated --no-project --with dist/*.tar.gz python -m fsweep --help
      - name: publish
        run: uv publish
